#!/usr/bin/env bash
# This script displays numbers from 1 to 100 with FizzBuzz, Fizz, and Buzz replacements

for ((i=1; i<=100; i++))
do
    if (( i % 3 == 0)) && (( i % 5 == 0)); then
        echo "$i. FizzBuzz"
     elif (( i % 3 == 0 )); then
        echo "$i. Fizz"
    elif (( i % 5 == 0 )); then
        echo "$i. Buzz"
    else
        echo "$i. $i"
    fi
done
