#!/usr/bin/env bash
# This script displays the content of /etc/passwd with username, user id, and home directory path

while IFS=':' read -r username _ userid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
done < /etc/passwd
