#!/usr/bin/env bash
# This script displays "Best School" 10 times, with a special case on the 9th iteration

counter=1
while [ $counter -lt 10 ]; do
  if [ $counter -eq 8 ]; then
    echo -e "Best School\nHi"
  else
    echo "Best School"
  fi
  counter=$((counter+1))
done
