#!/bin/bash
# This script displays the content of the current directory in a list format where only the part of the name after the first dash is displayed
for file in * # loop through all files in the current directory
do
  if [[ $file != .* ]] # if the file does not start with a dot (hidden file)
  then
    echo $file | cut -d - -f 2- # display only the part of the name after the first dash
  fi
done
