#!/usr/bin/env bash

# Create the PID file
echo $$ > /var/run/myscript.pid

# Define the signal handlers
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM
trap 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

